name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g @google/clasp
          
      - name: Validate Apps Script files
        run: |
          # Check for syntax errors in .gs files
          for file in *.gs; do
            if [ -f "$file" ]; then
              echo "Validating $file..."
              # Basic syntax validation - check for common issues
              if grep -q "function.*{" "$file"; then
                echo "✓ $file appears to have valid function syntax"
              else
                echo "⚠ $file may have syntax issues"
              fi
            fi
          done
          
      - name: Validate JSON files
        run: |
          # Validate appsscript.json if it exists
          if [ -f "appsscript.json" ]; then
            echo "Validating appsscript.json..."
            cat appsscript.json | jq . > /dev/null && echo "✓ appsscript.json is valid JSON"
          fi
          
      - name: Check for required files
        run: |
          echo "Checking for required add-on files..."
          required_files=("zoho_integration_core.gs" "zoho_validation.gs" "zoho_config.gs" "zoho_triggers.gs")
          for file in "${required_files[@]}"; do
            if [ -f "$file" ]; then
              echo "✓ $file found"
            else
              echo "✗ $file missing"
              exit 1
            fi
          done
